In [2]:
# import the pandas library
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randn(5, 3), index=['a', 'c', 'e', 'f',
'h'],columns=['one', 'two', 'three'])
print( df)
df = df.reindex(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])

print( df)
print (df['one'].median())
print (df['one'].isnull())
#Total missing value for each attribute
print (df.isnull().sum())
#any missing values?
print (df['one'].isnull().values.any())
#Total no. of missing values
print (df.isnull().sum().sum())

        one       two     three
a -0.252486  0.657731 -1.242945
c -0.399644  0.153107 -0.706340
e  1.327318 -2.288123  1.095958
f  2.208380  1.477273  1.719006
h  0.368150 -1.233653 -0.416261
        one       two     three
a -0.252486  0.657731 -1.242945
b       NaN       NaN       NaN
c -0.399644  0.153107 -0.706340
d       NaN       NaN       NaN
e  1.327318 -2.288123  1.095958
f  2.208380  1.477273  1.719006
g       NaN       NaN       NaN
h  0.368150 -1.233653 -0.416261
0.3681500404430499
a    False
b     True
c    False
d     True
e    False
f    False
g     True
h    False
Name: one, dtype: bool
one      3
two      3
three    3
dtype: int64
True
9

In [3]:
print ("NaN replaced with '0':")
print( df.fillna(0))

NaN replaced with '0':
        one       two     three
a -0.252486  0.657731 -1.242945
b  0.000000  0.000000  0.000000
c -0.399644  0.153107 -0.706340
d  0.000000  0.000000  0.000000
e  1.327318 -2.288123  1.095958
f  2.208380  1.477273  1.719006
g  0.000000  0.000000  0.000000
h  0.368150 -1.233653 -0.416261

In [4]:
print(df)
print( df.fillna(method='pad'))

        one       two     three
a -0.252486  0.657731 -1.242945
b       NaN       NaN       NaN
c -0.399644  0.153107 -0.706340
d       NaN       NaN       NaN
e  1.327318 -2.288123  1.095958
f  2.208380  1.477273  1.719006
g       NaN       NaN       NaN
h  0.368150 -1.233653 -0.416261
        one       two     three
a -0.252486  0.657731 -1.242945
b -0.252486  0.657731 -1.242945
c -0.399644  0.153107 -0.706340
d -0.399644  0.153107 -0.706340
e  1.327318 -2.288123  1.095958
f  2.208380  1.477273  1.719006
g  2.208380  1.477273  1.719006
h  0.368150 -1.233653 -0.416261

C:\Users\Dipak\AppData\Local\Temp\ipykernel_14468\1346297352.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  print( df.fillna(method='pad'))

In [5]:
print(df)
print( df.fillna(method='bfill'))

        one       two     three
a -0.252486  0.657731 -1.242945
b       NaN       NaN       NaN
c -0.399644  0.153107 -0.706340
d       NaN       NaN       NaN
e  1.327318 -2.288123  1.095958
f  2.208380  1.477273  1.719006
g       NaN       NaN       NaN
h  0.368150 -1.233653 -0.416261
        one       two     three
a -0.252486  0.657731 -1.242945
b -0.399644  0.153107 -0.706340
c -0.399644  0.153107 -0.706340
d  1.327318 -2.288123  1.095958
e  1.327318 -2.288123  1.095958
f  2.208380  1.477273  1.719006
g  0.368150 -1.233653 -0.416261
h  0.368150 -1.233653 -0.416261

C:\Users\Dipak\AppData\Local\Temp\ipykernel_14468\190117098.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  print( df.fillna(method='bfill'))

In [6]:
print(df)
print( df.dropna())

        one       two     three
a -0.252486  0.657731 -1.242945
b       NaN       NaN       NaN
c -0.399644  0.153107 -0.706340
d       NaN       NaN       NaN
e  1.327318 -2.288123  1.095958
f  2.208380  1.477273  1.719006
g       NaN       NaN       NaN
h  0.368150 -1.233653 -0.416261
        one       two     three
a -0.252486  0.657731 -1.242945
c -0.399644  0.153107 -0.706340
e  1.327318 -2.288123  1.095958
f  2.208380  1.477273  1.719006
h  0.368150 -1.233653 -0.416261

In [7]:
#Interpolation of immediate data before and after it (average is taken)

print(df.interpolate())

        one       two     three
a -0.252486  0.657731 -1.242945
b -0.326065  0.405419 -0.974642
c -0.399644  0.153107 -0.706340
d  0.463837 -1.067508  0.194809
e  1.327318 -2.288123  1.095958
f  2.208380  1.477273  1.719006
g  1.288265  0.121810  0.651373
h  0.368150 -1.233653 -0.416261

In [8]:
import pandas as pd

df = pd.read_csv("train.csv")
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [9]:
to_drop = ['Gender','Married']
#df.drop(columns=to_drop, inplace=True)
df.drop(to_drop, inplace=True, axis=1)

In [9]:
df.head()

,Loan_ID,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [10]:
df = pd.DataFrame({
    'brand': ['Yum Yum', 'Yum Yum', 'Indomie', 'Indomie', 'Indomie'],
    'style': ['cup', 'cup', 'cup', 'pack', 'pack'],
    'rating': [4, 4, 3.5, 15, 5]
})
df

     brand style  rating
0  Yum Yum   cup     4.0
1  Yum Yum   cup     4.0
2  Indomie   cup     3.5
3  Indomie  pack    15.0
4  Indomie  pack     5.0

In [11]:
df.drop_duplicates()

     brand style  rating
0  Yum Yum   cup     4.0
2  Indomie   cup     3.5
3  Indomie  pack    15.0
4  Indomie  pack     5.0

In [12]:
#To remove duplicates on specific column(s), use subset.
df.drop_duplicates(subset=['brand'])

     brand style  rating
0  Yum Yum   cup     4.0
2  Indomie   cup     3.5

In [13]:
#To remove duplicates on specific column(s), use subset.
#to remove duplicates and keep last occurrences, use keep.
df.drop_duplicates(subset=['brand', 'style'], keep='last')

     brand style  rating
1  Yum Yum   cup     4.0
2  Indomie   cup     3.5
4  Indomie  pack     5.0

In [ ]:
#https://pandas.pydata.org/docs/reference/frame.html